### ISSUE TITLE
Issue with the setup code base on local machine

### ISSUE THREAD

**Issue by shaxzad** [swellstores/horizon#22]
Try to setup this code base on my local machine also try with the GitHub online codebase the issue is the same.

Any one can help me?

![image](https://user-images.githubusercontent.com/24851240/209012198-58511b33-14c4-4d69-b1e4-aa330c912703.png)

**Comment by AdrianRC** [comment]
Hey @shaxzad, seems like the `source` command we were using inside of the `sync` npm script is not compatible with your shell. Could you please retry on this branch? https://github.com/swellstores/horizon/tree/fork/fix-env-src

Thanks and sorry for the inconveniences.

**Comment by shaxzad** [comment]
Hi @AdrianRC 

Thanks for the support.
It's worked on that branch.
I still facing some issues here when run the command `npm run dev`

![image](https://user-images.githubusercontent.com/24851240/209234327-c6eaa846-bcfb-4703-a283-77de9035c1e3.png)

**Comment by agsmartwolf** [comment]
@shaxzad  I had the same issue on your first screenshot. So i've reinstall node as in guide via nvm - ran `nvm install` command and then `npm install` and everything was setup so i could ran app.

**Comment by ana-estrela** [comment]
Thank you @agsmartwolf for your help!

@shaxzad were you able to fix your issue?

**Comment by holden** [comment]
I'm also having this issue, it get through almost everything but fails when it reaches `sync:content-blocks`

Using the `[fork/fix-env-src](https://github.com/swellstores/horizon/tree/fork/fix-env-src)` gets me further but it still crashes towards the end with:

```
[sync] [content-blocks] - Pushing Quiz model.
[sync] [content-blocks] ✔ Successfully pushed theme.horizon.quiz model to cirqus-marketplace store.
[sync] [content-blocks] - Pushing Question page model.
[sync] [content-blocks] ✔ Successfully pushed theme.horizon.quiz_question model to cirqus-marketplace store.
[sync] [content-blocks] - Pushing Transition page model.
[sync] [content-blocks] ✔ Successfully pushed theme.horizon.quiz_transition model to cirqus-marketplace store.
[sync] [content-blocks] - Pushing Customer reviews model.
[sync] [content-blocks] ✔ Successfully pushed theme.horizon.reviews model to cirqus-marketplace store.
[sync] [content-blocks] npm run sync:content-blocks exited with code 0
[sync] npm run sync exited with code 1
npm ERR! code 1
npm ERR! path /Users/holden/Code/paid-projects/cirqus-horizon
npm ERR! command failed
npm ERR! command sh -c -- husky install && if [ -f codegen.yml ] && [ -f build-utils/generate-theme.mjs ]; then npm run setup; fi
```

The logs don't give much else:

```
906 error command failed
907 error command sh -c -- husky install && if [ -f codegen.yml ] && [ -f build-utils/generate-theme.mjs ]; then npm run setup; fi
908 verbose exit 1
909 timing npm Completed in 45898ms
910 verbose code 1
```

Any ideas?

Thanks

**Comment by ana-estrela** [comment]
Hey @holden thank you for bringing this up to our attention! We’re currently to solve this issue as soon as possible as we’ve made a few updates to our system our the last couple of days that might have affected Horizon. We’ll let you know once it has been fixed.

**Comment by logeshswell** [comment]
Please run the below set of commands in the same order to get the setup working fine locally.

```bash
git clone https://github.com/swellstores/horizon.git
cd horizon

nvm install
npm install -g npm@8
```

Create a `.env` file in the root directory with the following content:
```env
NEXT_PUBLIC_SWELL_STORE_URL=https://STORE_ID.swell.store
NEXT_PUBLIC_SWELL_PUBLIC_KEY=
SWELL_STORE_ID=STORE_ID
SWELL_SECRET_KEY=
```

Now, run the below command
```bash
npm install
```

Please find the logs below:
```bash
user@Logeshs-MacBook-Pro-2 Desktop % git clone https://github.com/swellstores/horizon.git
Cloning into 'horizon'...
remote: Enumerating objects: 1411, done.
remote: Counting objects: 100% (644/644), done.
remote: Compressing objects: 100% (451/451), done.
remote: Total 1411 (delta 269), reused 372 (delta 181), pack-reused 767
Receiving objects: 100% (1411/1411), 17.24 MiB | 11.37 MiB/s, done.
Resolving deltas: 100% (315/315), done.
user@Logeshs-MacBook-Pro-2 Desktop % 
user@Logeshs-MacBook-Pro-2 Desktop % 
user@Logeshs-MacBook-Pro-2 Desktop % cd horizon 
user@Logeshs-MacBook-Pro-2 horizon % nvm install
Found '/Users/user/Desktop/horizon/.nvmrc' with version <16.18.1>
v16.18.1 is already installed.
Now using node v16.18.1 (npm v8.19.4)
user@Logeshs-MacBook-Pro-2 horizon % 
user@Logeshs-MacBook-Pro-2 horizon % 
user@Logeshs-MacBook-Pro-2 horizon % nvm use
Found '/Users/user/Desktop/horizon/.nvmrc' with version <16.18.1>
Now using node v16.18.1 (npm v8.19.4)
user@Logeshs-MacBook-Pro-2 horizon % 
user@Logeshs-MacBook-Pro-2 horizon % 
user@Logeshs-MacBook-Pro-2 horizon % npm install -g npm@8

changed 16 packages, and audited 212 packages in 1s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
user@Logeshs-MacBook-Pro-2 horizon % 
user@Logeshs-MacBook-Pro-2 horizon %
user@Logeshs-MacBook-Pro-2 horizon % npm install
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: relay-compiler@12.0.0
npm WARN Found: graphql@16.3.0
npm WARN node_modules/graphql
npm WARN   graphql@"^16.3.0" from the root project
npm WARN   69 more (@graphql-codegen/cli, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer graphql@"^15.0.0" from relay-compiler@12.0.0
npm WARN node_modules/relay-compiler
npm WARN   relay-compiler@"12.0.0" from @graphql-tools/relay-operation-optimizer@6.4.5
npm WARN   node_modules/@graphql-tools/relay-operation-optimizer
npm WARN 
npm WARN Conflicting peer dependency: graphql@15.8.0
npm WARN node_modules/graphql
npm WARN   peer graphql@"^15.0.0" from relay-compiler@12.0.0
npm WARN   node_modules/relay-compiler
npm WARN     relay-compiler@"12.0.0" from @graphql-tools/relay-operation-optimizer@6.4.5
npm WARN     node_modules/@graphql-tools/relay-operation-optimizer
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: webpack-filter-warnings-plugin@1.2.1
npm WARN Found: webpack@5.70.0
npm WARN node_modules/webpack
npm WARN   dev webpack@"^5.69.1" from the root project
npm WARN   24 more (@pmmmwh/react-refresh-webpack-plugin, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer webpack@"^2.0.0 || ^3.0.0 || ^4.0.0" from webpack-filter-warnings-plugin@1.2.1
npm WARN node_modules/webpack-filter-warnings-plugin
npm WARN   webpack-filter-warnings-plugin@"^1.2.1" from @storybook/builder-webpack4@6.5.10
npm WARN   node_modules/@storybook/builder-webpack4
npm WARN 
npm WARN Conflicting peer dependency: webpack@4.46.0
npm WARN node_modules/webpack
npm WARN   peer webpack@"^2.0.0 || ^3.0.0 || ^4.0.0" from webpack-filter-warnings-plugin@1.2.1
npm WARN   node_modules/webpack-filter-warnings-plugin
npm WARN     webpack-filter-warnings-plugin@"^1.2.1" from @storybook/builder-webpack4@6.5.10
npm WARN     node_modules/@storybook/builder-webpack4

> @swell/horizon@0.4.0 prepare
> husky install && if [ -f codegen.yml ] && [ -f build-utils/generate-theme.mjs ]; then npm run setup; fi

husky - Git hooks installed

> @swell/horizon@0.4.0 setup
> npm run sync && npm run graphql:generate && npm run theme:generate


> @swell/horizon@0.4.0 sync
> set -a && if [ -f .env ]; then source .env; fi && npm run sync:defaults && npm run sync:content-blocks && npm run sync:editor


> @swell/horizon@0.4.0 sync:defaults
> swell storefront settings push settings -f ./config/defaults.json --strategy "defaults" --store $SWELL_STORE_ID --secret-key $SWELL_SECRET_KEY

✔ Successfully updated settings to logesh-test-1 store.

> @swell/horizon@0.4.0 sync:content-blocks
> ls ./config/content/*.json | xargs -L 1 swell model push --store $SWELL_STORE_ID --secret-key $SWELL_SECRET_KEY --strategy "merge" --content -f

✔ Successfully pushed theme.horizon.categories_preview model to logesh-test-1 store.
✔ Successfully pushed theme.horizon.category model to logesh-test-1 store.
✔ Successfully pushed theme.horizon.divider model to logesh-test-1 store.
✔ Successfully pushed theme.horizon.full_width_media model to logesh-test-1 store.
✔ Successfully pushed theme.horizon.heading_with_text model to logesh-test-1 store.
✔ Successfully pushed theme.horizon.memberships model to logesh-test-1 store.
✔ Successfully pushed theme.horizon.multiple_features model to logesh-test-1 store.
✔ Successfully pushed theme.horizon.multiple_panels model to logesh-test-1 store.
✔ Successfully pushed theme.horizon.page model to logesh-test-1 store.
✔ Successfully pushed theme.horizon.press_mentions_carousel model to logesh-test-1 store.
✔ Successfully pushed theme.horizon.product model to logesh-test-1 store.
✔ Successfully pushed theme.horizon.products_preview model to logesh-test-1 store.
✔ Successfully pushed theme.horizon.quiz model to logesh-test-1 store.
✔ Successfully pushed theme.horizon.quiz_question model to logesh-test-1 store.
✔ Successfully pushed theme.horizon.quiz_transition model to logesh-test-1 store.
✔ Successfully pushed theme.horizon.reviews model to logesh-test-1 store.

> @swell/horizon@0.4.0 sync:editor
> swell storefront settings push editor -f config/editor.json --strategy "merge" --store $SWELL_STORE_ID --secret-key $SWELL_SECRET_KEY

✔ Successfully updated editor settings to logesh-test-1 store.

> @swell/horizon@0.4.0 graphql:generate
> graphql-codegen --config codegen.yml -r dotenv/config

✔ Parse Configuration
✔ Generate outputs

> @swell/horizon@0.4.0 theme:generate
> node -r dotenv/config ./build-utils/generate-theme.mjs

file:///Users/user/Desktop/horizon/build-utils/styles.mjs:14
  Object.entries(object).forEach(([key, value]) => {
         ^

TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at getVarsFromObject (file:///Users/user/Desktop/horizon/build-utils/styles.mjs:14:10)
    at generateCssVars (file:///Users/user/Desktop/horizon/build-utils/styles.mjs:32:21)
    at file:///Users/user/Desktop/horizon/build-utils/generate-theme.mjs:12:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm ERR! code 1
npm ERR! path /Users/user/Desktop/horizon
npm ERR! command failed
npm ERR! command sh -c -- husky install && if [ -f codegen.yml ] && [ -f build-utils/generate-theme.mjs ]; then npm run setup; fi

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2023-04-12T11_59_58_997Z-debug-0.log
user@Logeshs-MacBook-Pro-2 horizon % 
user@Logeshs-MacBook-Pro-2 horizon % 
user@Logeshs-MacBook-Pro-2 horizon % 
```

You will encounter an error in the step of `theme:generate` for which our team is working on the fix and you can get it resolved at the earliest.

**Comment by holden** [comment]
I tried everything using the current vanilla main branch.  I only tried the other branch I mentioned because `main` it wasn't working.

The changes to package.json from your commit seemed to work a bit further but I got errors on `npm run theme:generate` (which I guess is the same as you) but also on `sync:content-blocks` ?

But closer than before!

```
➜  horizon git:(main) npm install
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: relay-compiler@12.0.0
npm WARN Found: graphql@16.3.0
npm WARN node_modules/graphql
npm WARN   graphql@"^16.3.0" from the root project
npm WARN   66 more (@graphql-codegen/introspection, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer graphql@"^15.0.0" from relay-compiler@12.0.0
npm WARN node_modules/relay-compiler
npm WARN   relay-compiler@"12.0.0" from @graphql-tools/relay-operation-optimizer@6.4.5
npm WARN   node_modules/@graphql-tools/relay-operation-optimizer
npm WARN 
npm WARN Conflicting peer dependency: graphql@15.8.0
npm WARN node_modules/graphql
npm WARN   peer graphql@"^15.0.0" from relay-compiler@12.0.0
npm WARN   node_modules/relay-compiler
npm WARN     relay-compiler@"12.0.0" from @graphql-tools/relay-operation-optimizer@6.4.5
npm WARN     node_modules/@graphql-tools/relay-operation-optimizer
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: webpack-filter-warnings-plugin@1.2.1
npm WARN Found: webpack@5.70.0
npm WARN node_modules/webpack
npm WARN   dev webpack@"^5.69.1" from the root project
npm WARN   24 more (@pmmmwh/react-refresh-webpack-plugin, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer webpack@"^2.0.0 || ^3.0.0 || ^4.0.0" from webpack-filter-warnings-plugin@1.2.1
npm WARN node_modules/webpack-filter-warnings-plugin
npm WARN   webpack-filter-warnings-plugin@"^1.2.1" from @storybook/builder-webpack4@6.5.10
npm WARN   node_modules/@storybook/builder-webpack4
npm WARN 
npm WARN Conflicting peer dependency: webpack@4.46.0
npm WARN node_modules/webpack
npm WARN   peer webpack@"^2.0.0 || ^3.0.0 || ^4.0.0" from webpack-filter-warnings-plugin@1.2.1
npm WARN   node_modules/webpack-filter-warnings-plugin
npm WARN     webpack-filter-warnings-plugin@"^1.2.1" from @storybook/builder-webpack4@6.5.10
npm WARN     node_modules/@storybook/builder-webpack4

> @swell/horizon@0.4.0 prepare
> husky install && if [ -f codegen.yml ] && [ -f build-utils/generate-theme.mjs ]; then npm run setup; fi

husky - Git hooks installed

> @swell/horizon@0.4.0 setup
> concurrently "npm:sync" "npm:graphql:generate" "npm:theme:generate"

[sync] 
[sync] > @swell/horizon@0.4.0 sync
[sync] > dotenv concurrently "npm:sync:*"
[sync] 
[graphql:generate] 
[graphql:generate] > @swell/horizon@0.4.0 graphql:generate
[graphql:generate] > graphql-codegen --config codegen.yml -r dotenv/config
[graphql:generate] 
[theme:generate] 
[theme:generate] > @swell/horizon@0.4.0 theme:generate
[theme:generate] > node -r dotenv/config ./build-utils/generate-theme.mjs
[theme:generate] 
[sync] [content-blocks] 
[sync] [content-blocks] > @swell/horizon@0.4.0 sync:content-blocks
[sync] [content-blocks] > ls ./config/content/*.json | xargs -L 1 swell model push --store $SWELL_STORE_ID --secret-key $SWELL_SECRET_KEY --strategy "merge" --content -f
[sync] [content-blocks] 
[sync] [defaults] 
[sync] [defaults] > @swell/horizon@0.4.0 sync:defaults
[sync] [defaults] > swell storefront settings push settings -f ./config/defaults.json --strategy "defaults" --store $SWELL_STORE_ID --secret-key $SWELL_SECRET_KEY
[sync] [defaults] 
[sync] [editor] 
[sync] [editor] > @swell/horizon@0.4.0 sync:editor
[sync] [editor] > swell storefront settings push editor -f config/editor.json --strategy "merge" --store $SWELL_STORE_ID --secret-key $SWELL_SECRET_KEY
[sync] [editor] 
[sync] [content-blocks] - Pushing Categories Preview model.
[sync] [editor] - Pushing editor settings
[sync] [defaults] - Pushing settings
[graphql:generate] [15:12:09] Parse configuration [started]
[graphql:generate] [15:12:09] Parse configuration [completed]
[graphql:generate] [15:12:09] Generate outputs [started]
[graphql:generate] [15:12:09] Generate ./graphql.schema.json [started]
[graphql:generate] [15:12:09] Generate lib/graphql/generated/sdk.ts [started]
[graphql:generate] [15:12:09] Load GraphQL schemas [started]
[graphql:generate] [15:12:09] Load GraphQL schemas [started]
[sync] [defaults] ✖ Cannot convert undefined or null to object
[sync] [defaults] npm run sync:defaults exited with code 1
[graphql:generate] [15:12:10] Load GraphQL schemas [completed]
[graphql:generate] [15:12:10] Load GraphQL schemas [completed]
[graphql:generate] [15:12:10] Load GraphQL documents [started]
[graphql:generate] [15:12:10] Load GraphQL documents [started]
[graphql:generate] [15:12:10] Load GraphQL documents [completed]
[graphql:generate] [15:12:10] Load GraphQL documents [completed]
[graphql:generate] [15:12:10] Generate [started]
[graphql:generate] [15:12:10] Generate [started]
[graphql:generate] [15:12:10] Generate [completed]
[graphql:generate] [15:12:10] Generate [completed]
[graphql:generate] [15:12:10] Generate ./graphql.schema.json [completed]
[graphql:generate] [15:12:10] Generate lib/graphql/generated/sdk.ts [completed]
[graphql:generate] [15:12:10] Generate outputs [completed]
[graphql:generate] npm run graphql:generate exited with code 0
[sync] [content-blocks] ✔ Successfully pushed theme.horizon.categories_preview model to cirqus-marketplace store.
[sync] [content-blocks] - Pushing Category list page model.
[theme:generate] file:///Users/holdenthomas/Code/paid-projects/horizon/build-utils/styles.mjs:14
[theme:generate]   Object.entries(object).forEach(([key, value]) => {
[theme:generate]          ^
[theme:generate] 
[theme:generate] TypeError: Cannot convert undefined or null to object
[theme:generate]     at Function.entries (<anonymous>)
[theme:generate]     at getVarsFromObject (file:///Users/holdenthomas/Code/paid-projects/horizon/build-utils/styles.mjs:14:10)
[theme:generate]     at generateCssVars (file:///Users/holdenthomas/Code/paid-projects/horizon/build-utils/styles.mjs:32:21)
[theme:generate]     at file:///Users/holdenthomas/Code/paid-projects/horizon/build-utils/generate-theme.mjs:12:19
[theme:generate]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[theme:generate] npm run theme:generate exited with code 1
[sync] [editor] ✔ Successfully updated editor settings to cirqus-marketplace store.
[sync] [editor] npm run sync:editor exited with code 0
[sync] [content-blocks] ✔ Successfully pushed theme.horizon.category model to cirqus-marketplace store.
[sync] [content-blocks] - Pushing Divider model.
[sync] [content-blocks] ✔ Successfully pushed theme.horizon.divider model to cirqus-marketplace store.
[sync] [content-blocks] - Pushing Full width media model.
[sync] [content-blocks] ✔ Successfully pushed theme.horizon.full_width_media model to cirqus-marketplace store.
[sync] [content-blocks] - Pushing Heading with text model.
[sync] [content-blocks] ✔ Successfully pushed theme.horizon.heading_with_text model to cirqus-marketplace store.
[sync] [content-blocks] - Pushing Memberships model.
[sync] [content-blocks] ✔ Successfully pushed theme.horizon.memberships model to cirqus-marketplace store.
[sync] [content-blocks] - Pushing Multiple features model.
[sync] [content-blocks] ✔ Successfully pushed theme.horizon.multiple_features model to cirqus-marketplace store.
[sync] [content-blocks] - Pushing Multiple panels model.
[sync] [content-blocks] ✔ Successfully pushed theme.horizon.multiple_panels model to cirqus-marketplace store.
[sync] [content-blocks] - Pushing Page model.
[sync] [content-blocks] ✔ Successfully pushed theme.horizon.page model to cirqus-marketplace store.
[sync] [content-blocks] - Pushing Press mentions carousel model.
[sync] [content-blocks] ✔ Successfully pushed theme.horizon.press_mentions_carousel model to cirqus-marketplace store.
[sync] [content-blocks] - Pushing Product detail page model.
[sync] [content-blocks] ✔ Successfully pushed theme.horizon.product model to cirqus-marketplace store.
[sync] [content-blocks] - Pushing Products preview model.
[sync] [content-blocks] ✔ Successfully pushed theme.horizon.products_preview model to cirqus-marketplace store.
[sync] [content-blocks] - Pushing Quiz model.
[sync] [content-blocks] ✔ Successfully pushed theme.horizon.quiz model to cirqus-marketplace store.
[sync] [content-blocks] - Pushing Question page model.
[sync] [content-blocks] ✔ Successfully pushed theme.horizon.quiz_question model to cirqus-marketplace store.
[sync] [content-blocks] - Pushing Transition page model.
[sync] [content-blocks] ✔ Successfully pushed theme.horizon.quiz_transition model to cirqus-marketplace store.
[sync] [content-blocks] - Pushing Customer reviews model.
[sync] [content-blocks] ✔ Successfully pushed theme.horizon.reviews model to cirqus-marketplace store.
[sync] [content-blocks] npm run sync:content-blocks exited with code 0
[sync] npm run sync exited with code 1
npm ERR! code 1
npm ERR! path /Users/holdenthomas/Code/paid-projects/horizon
npm ERR! command failed
npm ERR! command sh -c -- husky install && if [ -f codegen.yml ] && [ -f build-utils/generate-theme.mjs ]; then npm run setup; fi

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/holdenthomas/.npm/_logs/2023-04-12T13_11_49_317Z-debug-0.log
```

**Comment by logeshswell** [comment]
No, as you can see `npm run sync:content-blocks exited with code 0` which means that it is successfully executed and exited.
While `npm run theme:generate exited with code 1` is excepted until the fix is rolled out.

**Comment by stoqe** [comment]
just keeping myself in the loop here (so i get updated on the fix too)

**Comment by holden** [comment]
Hi, just curious about an update. Has this issue been resolved yet?  Thanks

**Comment by logeshswell** [comment]
@holden @stoqe We are almost very close to rollout the fix in production. I will keep you posted if it's deployed.

**Comment by holden** [comment]
Have you guys managed to plug the hole? ;-)

**Comment by unknownsouls** [comment]
following

**Comment by codeclouds-team** [comment]
following

**Comment by shumiyao** [comment]
so isnt Swell trying to sunset or running short of resources for some extra like this project?
I signed up for swell and canceled on the next day as soon as I found out that they are not really updating repos for frontends. (origin already sunset)

**Comment by shumiyao** [comment]
ok I see, so you meant you used to have a hosting solution before?

https://developers.swell.is/storefronts/origin
![ScreenShot 2023-05-19 at 2 05 05 PM](https://github.com/swellstores/horizon/assets/50849841/56e25ead-3dc6-4819-8ffb-798c17e70504)

I hope that you will fix the problem (`Cannot convert undefined or null to object` in running `npm run install`) soon so that we can get started.

**Comment by ericingram** [comment]
The theme editor will work as it did, and live-preview will work for apps that support it like Origin and Horizon. You can trigger builds manually from another system, and soon we will introduce a way to trigger an external publish webhook from the editor.

We found that a lot of people were having trouble with the hosted system (our fault) while developers generally preferred to host on other systems any way. We have limited resources, and this shift was necessary to make sure we could dedicate efforts to larger issues.

Most of the issues mentioned in the forum are caused by a missing configuration. We're going to release a new CLI version that should solve this early next week.

**Comment by logeshswell** [comment]
@stoqe @shaxzad @unknownsouls @codeclouds-team @shumiyao
Could you please share your store-id so that I can fix the configurations in the meantime of rolling out the fix?

**Comment by shumiyao** [comment]
@logeshswell 

Thank you. mine is `sweet-morango`

Note: I tried the `fix/swell-cli-sdv2` branch yesterday, ended up with error about "SwellCategory". Would it be a problem?

**Comment by logeshswell** [comment]
@shumiyao Your storefront should work fine as expected now.
<img width="1512" alt="Screenshot 2023-05-25 at 12 40 23 AM" src="https://github.com/swellstores/horizon/assets/100766131/7d44a703-12aa-49cb-9a64-e005eb7f01aa">

**Comment by shumiyao** [comment]
@logeshswell 
Thank you! It is now working!

----
Procedures:

1. Switch to `fix/swell-cli-sdv2` branch. (Added `SWELL_STOREFRONT_ID` to the .env file)
2. npm install  
3. npm run build
4. npm run start
5. Server accessible at http://localhost:3000

**Comment by racsou** [comment]
I'm having this problem with fix/swell-cli-sdv2 branch:
 Generate outputs
  ❯ Generate to ./graphql.schema.json
    ✖
      Failed to load schema from https://amazon-deals.swell.store/graphql:
      Could not obtain introspection result, received the following as response;
      { error: { code: "AUTHENTICATION", message: "You must authenticate with your public key. Also, make sure withCredentials is enabled fo…
      GraphQLError: Could not obtain introspection result, received the following as response;
      { error: { code: "AUTHENTICATION", message: "You must authenticate with your public key. Also, make sure withCredentials is enabled fo…
      at createGraphQLError (/var/www/html/swell/horizon/node_modules/@graphql-tools/wrap/node_modules/@graphql-tools/utils/cjs/errors.js:9:…
      at getSchemaFromIntrospection (/var/www/html/swell/horizon/node_modules/@graphql-tools/wrap/cjs/introspect.js:21:42)
      at /var/www/html/swell/horizon/node_modules/@graphql-tools/wrap/cjs/introspect.js:36:32
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async UrlLoader.load (/var/www/html/swell/horizon/node_modules/@graphql-tools/url-loader/cjs/index.js:211:29)
      at async /var/www/html/swell/horizon/node_modules/@graphql-tools/load/cjs/load-typedefs/load-file.js:17:39
      at async Promise.all (index 5)
      at async loadFile (/var/www/html/swell/horizon/node_modules/@graphql-tools/load/cjs/load-typedefs/load-file.js:15:9)
      at async /var/www/html/swell/horizon/node_modules/@graphql-tools/load/cjs/load-typedefs/collect-sources.js:229:25
      GraphQL Code Generator supports:
      - ES Modules and CommonJS exports (export as default or named export "schema")
      - Introspection JSON File
      - URL of GraphQL endpoint
      - Multiple files with type definitions (glob expression)
      - String in config file
      Try to use one of above options and run codegen again.
    ◼ Load GraphQL documents
    ◼ Generate
  ❯ Generate to lib/graphql/generated/sdk.ts
    ✖
      Failed to load schema from https://amazon-deals.swell.store/graphql:
      Could not obtain introspection result, received the following as response;
      { error: { code: "AUTHENTICATION", message: "You must authenticate with your public key. Also, make sure withCredentials is enabled fo…
      GraphQLError: Could not obtain introspection result, received the following as response;
      { error: { code: "AUTHENTICATION", message: "You must authenticate with your public key. Also, make sure withCredentials is enabled fo…
      at createGraphQLError (/var/www/html/swell/horizon/node_modules/@graphql-tools/wrap/node_modules/@graphql-tools/utils/cjs/errors.js:9:…
      at getSchemaFromIntrospection (/var/www/html/swell/horizon/node_modules/@graphql-tools/wrap/cjs/introspect.js:21:42)
      at /var/www/html/swell/horizon/node_modules/@graphql-tools/wrap/cjs/introspect.js:36:32
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async UrlLoader.load (/var/www/html/swell/horizon/node_modules/@graphql-tools/url-loader/cjs/index.js:211:29)
      at async /var/www/html/swell/horizon/node_modules/@graphql-tools/load/cjs/load-typedefs/load-file.js:17:39
      at async Promise.all (index 5)
      at async loadFile (/var/www/html/swell/horizon/node_modules/@graphql-tools/load/cjs/load-typedefs/load-file.js:15:9)
      at async /var/www/html/swell/horizon/node_modules/@graphql-tools/load/cjs/load-typedefs/collect-sources.js:229:25
      GraphQL Code Generator supports:
      - ES Modules and CommonJS exports (export as default or named export "schema")
      - Introspection JSON File
      - URL of GraphQL endpoint
      - Multiple files with type definitions (glob expression)
      - String in config file
      Try to use one of above options and run codegen again.
    ◼ Load GraphQL documents
    ◼ Generate
                                                                              
it semms horizon dosen't generate lib/graphql/generated/sdk.ts
please help

**Comment by unknownsouls** [comment]
As above: Follow these steps, worked for me


Switch to fix/swell-cli-sdv2 branch. (Added SWELL_STOREFRONT_ID to the .env file)
npm install
npm run build
npm run start
Server accessible at http://localhost:3000/


Here is how: 
Clone the main horizon theme : git clone [URL of the repo] , after it is loaded
then switch to swell-cli-sdv2 branch (git checkout swell-cli-sdv2)
npm install
npm run build
npm run start
Server accessible at http://localhost:3000/

Main thing to note is that the switch requires the "SWELL_STOREFRONT_ID" added to the .env you created when you installed the main theme. All info is in your swell account.

Your .env will look something like this: 

NEXT_PUBLIC_SWELL_STORE_URL=https://xyzswell.store
NEXT_PUBLIC_SWELL_PUBLIC_KEY=pk_xyz
SWELL_STORE_ID=xyz
SWELL_SECRET_KEY=xyz
SWELL_STOREFRONT_ID=xyz
NEXT_PUBLIC_SWELL_EDITOR=true

**Comment by sags95** [comment]
The latest version of Horizon now includes fixes to a lot of the issues mentioned in this thread. Please pull the latest changes and run `npm install` , you'll also have to create a `SWELL_STOREFRONT_ID` env var. More info can be found [here](https://developers.swell.is/storefronts/horizon).

**Comment by fucha-co** [comment]
> @stoqe @shaxzad @unknownsouls @codeclouds-team @shumiyao Could you please share your store-id so that I can fix the horizon theme configurations in your stores in the meantime of rolling out the fix?

- i totally missed this mention @logeshswell 
- though i just started afresh today with the latest branch/version of Horizon theme and i still have the same local install issue
- do you need to do some updates to my store to fix the problem? if so the store is fucha.swell.store

**Comment by logeshswell** [comment]
@fucha-co Can you help me with the error logs?
