### ISSUE TITLE
Deployment failed in Vercel

### ISSUE THREAD

**Issue by rishiimmehra** [swellstores/horizon#42]
[10:24:05] Running build in Cleveland, USA (East) – cle1
[10:24:05] Cloning github.com/rishiimmehra/swell-horizon (Branch: main, Commit: cf96db4)
[10:24:05] Skipping build cache, deployment was triggered without cache.
[10:24:06] Cloning completed: 985.515ms
[10:24:06] Running "vercel build"
[10:24:07] Vercel CLI 28.17.0
[10:24:07] Installing dependencies...
[10:24:10] npm WARN ERESOLVE overriding peer dependency
[10:24:10] npm WARN While resolving: relay-compiler@12.0.0
[10:24:10] npm WARN Found: graphql@16.3.0
[10:24:10] npm WARN node_modules/graphql
[10:24:10] npm WARN   graphql@"^16.3.0" from the root project
[10:24:10] npm WARN   69 more (@graphql-codegen/cli, ...)
[10:24:10] npm WARN 
[10:24:10] npm WARN Could not resolve dependency:
[10:24:10] npm WARN peer graphql@"^15.0.0" from relay-compiler@12.0.0
[10:24:10] npm WARN node_modules/relay-compiler
[10:24:10] npm WARN   relay-compiler@"12.0.0" from @graphql-tools/relay-operation-optimizer@6.4.5
[10:24:10] npm WARN   node_modules/@graphql-tools/relay-operation-optimizer
[10:24:10] npm WARN 
[10:24:10] npm WARN Conflicting peer dependency: graphql@15.8.0
[10:24:10] npm WARN node_modules/graphql
[10:24:10] npm WARN   peer graphql@"^15.0.0" from relay-compiler@12.0.0
[10:24:10] npm WARN   node_modules/relay-compiler
[10:24:10] npm WARN     relay-compiler@"12.0.0" from @graphql-tools/relay-operation-optimizer@6.4.5
[10:24:10] npm WARN     node_modules/@graphql-tools/relay-operation-optimizer
[10:24:10] npm WARN ERESOLVE overriding peer dependency
[10:24:10] npm WARN While resolving: webpack-filter-warnings-plugin@1.2.1
[10:24:10] npm WARN Found: webpack@5.70.0
[10:24:10] npm WARN node_modules/webpack
[10:24:10] npm WARN   dev webpack@"^5.69.1" from the root project
[10:24:10] npm WARN   24 more (@pmmmwh/react-refresh-webpack-plugin, ...)
[10:24:10] npm WARN 
[10:24:10] npm WARN Could not resolve dependency:
[10:24:10] npm WARN peer webpack@"^2.0.0 || ^3.0.0 || ^4.0.0" from webpack-filter-warnings-plugin@1.2.1
[10:24:10] npm WARN node_modules/webpack-filter-warnings-plugin
[10:24:10] npm WARN   webpack-filter-warnings-plugin@"^1.2.1" from @storybook/builder-webpack4@6.5.10
[10:24:10] npm WARN   node_modules/@storybook/builder-webpack4
[10:24:10] npm WARN 
[10:24:10] npm WARN Conflicting peer dependency: webpack@4.46.0
[10:24:10] npm WARN node_modules/webpack
[10:24:10] npm WARN   peer webpack@"^2.0.0 || ^3.0.0 || ^4.0.0" from webpack-filter-warnings-plugin@1.2.1
[10:24:10] npm WARN   node_modules/webpack-filter-warnings-plugin
[10:24:10] npm WARN     webpack-filter-warnings-plugin@"^1.2.1" from @storybook/builder-webpack4@6.5.10
[10:24:10] npm WARN     node_modules/@storybook/builder-webpack4
[10:24:17] npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
[10:24:18] npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
[10:24:18] npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
[10:24:18] npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[10:24:18] npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
[10:24:18] npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
[10:24:18] npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
[10:24:18] npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
[10:24:23] npm WARN deprecated @types/tailwindcss@3.1.0: This is a stub types definition. tailwindcss provides its own type definitions, so you do not need this installed.
[10:24:27] npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
[10:24:27] npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
[10:24:36] npm WARN deprecated core-js@3.21.1: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
[10:24:36] npm WARN deprecated core-js-pure@3.21.1: core-js-pure@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js-pure.
[10:24:38] 
[10:24:38] > @swell/horizon@0.4.0 prepare
[10:24:38] > husky install && if [ -f codegen.yml ] && [ -f build-utils/generate-theme.mjs ]; then npm run setup; fi
[10:24:38] 
[10:24:38] husky - Git hooks installed
[10:24:39] 
[10:24:39] > @swell/horizon@0.4.0 setup
[10:24:39] > npm run sync && npm run graphql:generate && npm run theme:generate
[10:24:39] 
[10:24:39] 
[10:24:39] > @swell/horizon@0.4.0 sync
[10:24:39] > set -a && if [ -f .env ]; then source .env; fi && npm run sync:defaults && npm run sync:content-blocks && npm run sync:editor
[10:24:39] 
[10:24:39] 
[10:24:39] > @swell/horizon@0.4.0 sync:defaults
[10:24:39] > swell storefront settings push settings -f ./config/defaults.json --strategy "defaults" --store $SWELL_STORE_ID --secret-key $SWELL_SECRET_KEY
[10:24:39] 
[10:24:40] - Pushing settings
[10:24:41] ✔ Successfully updated settings to teess store.
[10:24:42] 
[10:24:42] > @swell/horizon@0.4.0 sync:content-blocks
[10:24:42] > ls ./config/content/*.json | xargs -L 1 swell model push --store $SWELL_STORE_ID --secret-key $SWELL_SECRET_KEY --strategy "merge" --content -f
[10:24:42] 
[10:24:42] - Pushing Categories Preview model.
[10:24:43] ✔ Successfully pushed theme.horizon.categories_preview model to teess store.
[10:24:43] - Pushing Category list page model.
[10:24:44] ✔ Successfully pushed theme.horizon.category model to teess store.
[10:24:44] - Pushing Divider model.
[10:24:46] ✔ Successfully pushed theme.horizon.divider model to teess store.
[10:24:46] - Pushing Full width media model.
[10:24:47] ✔ Successfully pushed theme.horizon.full_width_media model to teess store.
[10:24:48] - Pushing Heading with text model.
[10:24:49] ✔ Successfully pushed theme.horizon.heading_with_text model to teess store.
[10:24:49] - Pushing Memberships model.
[10:24:50] ✔ Successfully pushed theme.horizon.memberships model to teess store.
[10:24:50] - Pushing Multiple features model.
[10:24:51] ✔ Successfully pushed theme.horizon.multiple_features model to teess store.
[10:24:51] - Pushing Multiple panels model.
[10:24:52] ✔ Successfully pushed theme.horizon.multiple_panels model to teess store.
[10:24:52] - Pushing Page model.
[10:24:54] ✔ Successfully pushed theme.horizon.page model to teess store.
[10:24:54] - Pushing Press mentions carousel model.
[10:24:55] ✔ Successfully pushed theme.horizon.press_mentions_carousel model to teess store.
[10:24:55] - Pushing Product detail page model.
[10:24:57] ✔ Successfully pushed theme.horizon.product model to teess store.
[10:24:57] - Pushing Products preview model.
[10:24:58] ✔ Successfully pushed theme.horizon.products_preview model to teess store.
[10:24:58] - Pushing Quiz model.
[10:25:01] ✔ Successfully pushed theme.horizon.quiz model to teess store.
[10:25:01] - Pushing Question page model.
[10:25:02] ✔ Successfully pushed theme.horizon.quiz_question model to teess store.
[10:25:02] - Pushing Transition page model.
[10:25:03] ✔ Successfully pushed theme.horizon.quiz_transition model to teess store.
[10:25:03] - Pushing Customer reviews model.
[10:25:04] ✔ Successfully pushed theme.horizon.reviews model to teess store.
[10:25:04] 
[10:25:04] > @swell/horizon@0.4.0 sync:editor
[10:25:04] > swell storefront settings push editor -f config/editor.json --strategy "merge" --store $SWELL_STORE_ID --secret-key $SWELL_SECRET_KEY
[10:25:04] 
[10:25:05] - Pushing editor settings
[10:25:06] ✔ Successfully updated editor settings to teess store.
[10:25:07] 
[10:25:07] > @swell/horizon@0.4.0 graphql:generate
[10:25:07] > graphql-codegen --config codegen.yml -r dotenv/config
[10:25:07] 
[10:25:08] [STARTED] Parse Configuration
[10:25:08] [SUCCESS] Parse Configuration
[10:25:08] [STARTED] Generate outputs
[10:25:08] [STARTED] Generate to ./graphql.schema.json
[10:25:08] [STARTED] Generate to lib/graphql/generated/sdk.ts
[10:25:08] [STARTED] Load GraphQL schemas
[10:25:08] [STARTED] Load GraphQL schemas
[10:25:11] [FAILED] 
[10:25:11] [FAILED]         Failed to load schema from https://teess--dev.swell.store//graphql:
[10:25:11] [FAILED] 
[10:25:11] [FAILED]         Must provide query string.
[10:25:11] [FAILED]         GraphQLError: Must provide query string.
[10:25:11] [FAILED]     at createGraphQLError (/vercel/path0/node_modules/@graphql-tools/wrap/node_modules/@graphql-tools/utils/cjs/errors.js:9:12)
[10:25:11] [FAILED]     at /vercel/path0/node_modules/@graphql-tools/wrap/cjs/introspect.js:13:102
[10:25:11] [FAILED]     at Array.map (<anonymous>)
[10:25:11] [FAILED]     at getSchemaFromIntrospection (/vercel/path0/node_modules/@graphql-tools/wrap/cjs/introspect.js:13:58)
[10:25:11] [FAILED]     at /vercel/path0/node_modules/@graphql-tools/wrap/cjs/introspect.js:36:32
[10:25:11] [FAILED]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[10:25:11] [FAILED]     at async UrlLoader.load (/vercel/path0/node_modules/@graphql-tools/url-loader/cjs/index.js:211:29)
[10:25:11] [FAILED]     at async /vercel/path0/node_modules/@graphql-tools/load/cjs/load-typedefs/load-file.js:17:39
[10:25:11] [FAILED]     at async Promise.all (index 5)
[10:25:11] [FAILED]     at async loadFile (/vercel/path0/node_modules/@graphql-tools/load/cjs/load-typedefs/load-file.js:15:9)
[10:25:11] [FAILED] 
[10:25:11] [FAILED]         GraphQL Code Generator supports:
[10:25:11] [FAILED]           - ES Modules and CommonJS exports (export as default or named export "schema")
[10:25:11] [FAILED]           - Introspection JSON File
[10:25:11] [FAILED]           - URL of GraphQL endpoint
[10:25:11] [FAILED]           - Multiple files with type definitions (glob expression)
[10:25:11] [FAILED]           - String in config file
[10:25:11] [FAILED] 
[10:25:11] [FAILED]         Try to use one of above options and run codegen again.
[10:25:11] [FAILED] 
[10:25:11] [FAILED]       
[10:25:11] [FAILED] 
[10:25:11] [FAILED]         Failed to load schema from https://teess--dev.swell.store//graphql:
[10:25:11] [FAILED] 
[10:25:11] [FAILED]         Must provide query string.
[10:25:11] [FAILED]         GraphQLError: Must provide query string.
[10:25:11] [FAILED]     at createGraphQLError (/vercel/path0/node_modules/@graphql-tools/wrap/node_modules/@graphql-tools/utils/cjs/errors.js:9:12)
[10:25:11] [FAILED]     at /vercel/path0/node_modules/@graphql-tools/wrap/cjs/introspect.js:13:102
[10:25:11] [FAILED]     at Array.map (<anonymous>)
[10:25:11] [FAILED]     at getSchemaFromIntrospection (/vercel/path0/node_modules/@graphql-tools/wrap/cjs/introspect.js:13:58)
[10:25:11] [FAILED]     at /vercel/path0/node_modules/@graphql-tools/wrap/cjs/introspect.js:36:32
[10:25:11] [FAILED]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[10:25:11] [FAILED]     at async UrlLoader.load (/vercel/path0/node_modules/@graphql-tools/url-loader/cjs/index.js:211:29)
[10:25:11] [FAILED]     at async /vercel/path0/node_modules/@graphql-tools/load/cjs/load-typedefs/load-file.js:17:39
[10:25:11] [FAILED]     at async Promise.all (index 5)
[10:25:11] [FAILED]     at async loadFile (/vercel/path0/node_modules/@graphql-tools/load/cjs/load-typedefs/load-file.js:15:9)
[10:25:11] [FAILED] 
[10:25:11] [FAILED]         GraphQL Code Generator supports:
[10:25:11] [FAILED]           - ES Modules and CommonJS exports (export as default or named export "schema")
[10:25:11] [FAILED]           - Introspection JSON File
[10:25:11] [FAILED]           - URL of GraphQL endpoint
[10:25:11] [FAILED]           - Multiple files with type definitions (glob expression)
[10:25:11] [FAILED]           - String in config file
[10:25:11] [FAILED] 
[10:25:11] [FAILED]         Try to use one of above options and run codegen again.
[10:25:11] [FAILED] 
[10:25:11] [FAILED]       
[10:25:11] [SUCCESS] Generate outputs
[10:25:11] npm ERR! code 1
[10:25:11] npm ERR! path /vercel/path0
[10:25:11] npm ERR! command failed
[10:25:11] npm ERR! command sh -c -- husky install && if [ -f codegen.yml ] && [ -f build-utils/generate-theme.mjs ]; then npm run setup; fi
[10:25:11] 
[10:25:11] npm ERR! A complete log of this run can be found in:
[10:25:11] npm ERR!     /vercel/.npm/_logs/2023-03-19T04_54_07_949Z-debug-0.log
[10:25:11] Error: Command "npm install" exited with 1
[10:25:11] BUILD_UTILS_SPAWN_1: Command "npm install" exited with 1

**Comment by rishiimmehra** [comment]
I have fucked up with store URL in Environment Variables
